# Generated by Django 3.1.4 on 2021-02-12 21:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('my_password', models.CharField(blank=True, max_length=150, verbose_name='Password')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=255, verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(max_length=60)),
                ('track', models.CharField(choices=[('Academic', 'Academic'), ('Non-academic', 'Non-academic'), ('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('subject_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=64)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.strand')),
                ('subject', models.ManyToManyField(to='backend.Subject')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.yearlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.profile')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birthday')),
                ('status', models.CharField(choices=[('IS ASSIGNED', 'IS ASSIGNED'), ('NOT YET ASSIGNED', 'NOT YET ASSIGNED')], default='NOT YET ASSIGNED', max_length=64)),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Role')),
            ],
            options={
                'verbose_name_plural': 'Teacher Profile',
            },
            bases=('backend.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.profile')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birthday')),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Enrolled', 'Enrolled'), ('IS ASSIGNED', 'IS ASSIGNED'), ('NOT YET ASSIGNED', 'NOT YET ASSIGNED')], default='Registered', max_length=64)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Role')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
            ],
            options={
                'verbose_name_plural': 'Student Profile',
            },
            bases=('backend.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.teacher'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_grade', models.SmallIntegerField(default=75, verbose_name='Grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='AllStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.student',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
