# Generated by Django 3.1.4 on 2021-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Enrolled', 'Enrolled')], default='Registered', max_length=64),
        ),
    ]
